import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Next App - Main",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div className='min-h-screen flex'>
        <div className='min-w-52 h-screen bg-gray-600' />
        {children}
      </div>
  );
}
