import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
    title: "Next - Auth",
    description: "Generated by create next app",
};

export default function RootLayout(
    {
        children,
    }: Readonly<{
        children: React.ReactNode;
    }>
) {
    return (
        <div className='w-full min-h-screen flex items-center justify-center'>
            {children}
        </div>
    );
}
