@back_end_HostAddress = http://localhost:5003

GET {{back_end_HostAddress}}/weatherforecast/
Accept: application/json

###


# curl -X 'POST' 
#  'http://localhost:5003/login?useCookies=true' 
#  -H 'accept: application/json' 
#  -H 'Content-Type: application/json' 
#  -d '{
#  "email": "string@string",
#  "password": "string1"
#}'
POST http://localhost:5003/login?useCookies=true
accept: application/json
Content-Type: application/json

{
  "email": "string@string",
  "password": "string1"
}

###


